version: '3'
services:
  bk-agent:
    build: .
    environment:
     - BUILDKITE_AGENT_TOKEN=${BUILDKITE_AGENT_TOKEN}
     - SSH_AUTH_SOCK=/ssh-agent
    volumes:
      - ${SSH_AUTH_SOCK}:/ssh-agent
      - /var/run/docker.sock:/var/run/docker.sock
